title: RLW Blog
description: A website with a blog
footer_text: Copyright 2020 Ravindu Lashan
header_feature_image: ../uploads/pages.jpg
header_text: Blogging site of RLW
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
